# JoinCommands by PixelGuy75 Config File;
############################################################################
# {player} = the player that command will be executed towards;
# Command executed when player joins the game;
enablejoin: true
JoinCommand: 
- mw default OurSpawn
- mw tp \"{name}\" OurSpawn
# Command executed when player dies;
enabledeath: false
DeathCommand: 
- say {player} Died again...
# Command executed when player does /spawn or respawns into the game;
enablespawn: false
RespawnCommand: 
- tell {player} Welcome to spawn!
# Command executed when player leaves the game;
enableleave: false
LeaveCommand: 
- say {player} ragequit from the server!
